import {StyleSheet} from "react-native";
var dimensions=require("Dimensions");
var {width,height} =dimensions.get("window");
export default styles=StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:"#f6f6f8",
        position:"relative",
    },
    header:{
        width:width,
        height:44,
        position:"relative",
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor:"#666"
    },
    back:{
        width:10.5,
        height:20,
        position:"absolute",
        top:12,
        left:12,
        zIndex:999,
    },
    backImg:{
        width:10.5,
        height:20,
    },
    headerTitle:{
        flex:1,
        fontSize:15,
        color:"#333",
        lineHeight:44,
        textAlign:"center",
    },
    news:{
        position:"absolute",
        top:10,
        right:10,
    },
    newsImg:{
        width:25,
        height:25,
    },
    car:{
        position:"absolute",
        top:14,
        right:52,
    },
    carImg:{
        width:20,
        height:18.5
    },
    goodsImg:{
        width:width,
        height:375,
    },
    con:{
        height:175.5,
        paddingTop: 20,
        paddingBottom: 20,
        paddingLeft: 13,
        paddingRight: 13,
        backgroundColor:"#fff",
        marginBottom: 10,
    },
    contain:{
        flex:1,
    },
    conTop:{
        height:35,
        flexDirection: 'row',
        justifyContent:"space-between",
        marginBottom:16,
    },
    title:{
        fontSize:13,
        flexWrap: 'wrap',
        width:284.5,
        lineHeight:17,
        color:"#333"            
    },
    share:{
        width:24,
        height:35,
        alignItems: 'center',
        justifyContent:"space-between",
    },
    shareImg:{
        width:18,
        height:18,
    },
    shareTxt:{
        textAlign:"center",
        fontSize:12,
        color:"#333",
        lineHeight:12,
    },
    conBottom:{
        flexDirection:"row",
    },
    conPrice:{
        height:37.5
    },
    newPrice:{
        flexDirection:"row",
    },
    new1:{
        fontSize:12,
        color:"#888",
        lineHeight:15,
    },    
    new2:{
        fontSize:12,
        color:"#333",
        lineHeight:15,
    },
    new3:{
        fontSize:14,
        lineHeight:15,
        color:"#333",
    },
    oldPrice:{
        flexDirection:"row",
    },
    old1:{
        fontSize:12,
        color:"#888",
    },
    old2:{
        fontSize:12,
        color:"#888",
        textDecorationLine:"line-through",
    },
    gift:{
        height:20,
        backgroundColor:"#f7ae3c",
        paddingLeft:7,
        paddingRight:7,
        color:"#fff",
        fontSize:13,
        lineHeight:20,
        borderRadius:10,
        marginLeft: 16,
    },
    detail:{
        height:30,
        paddingTop:16,
        borderTopWidth: 1,
        borderTopColor:"#e6e6e6",
        flexDirection: 'row',
        justifyContent:"space-between"
    },
    det1:{
        fontSize:11,
    },
    datails:{
        marginTop: 10,
    },
    tabList:{
        backgroundColor:"#fff",
        flexDirection:"row",
        justifyContent:"space-between",
        paddingLeft:46,
        paddingRight:46,
        height:50,
    },
    subCtrl:{
        fontSize:14,
        color:"#888",
        lineHeight:50,
    },
    subCtrlActive:{
        fontSize:14,
        color:"#b71627",
        lineHeight:50,
    },
    tabCon:{
        height:50,
    },
    display:{
        width:width,
        height:height,
        position:"absolute",
        left:0,
        bottom:0,
        justifyContent:"flex-end",
    },
    footer:{
        width:width,
        height:49,
        flexDirection:"row",
        justifyContent:"flex-end",
        alignItems:"center",
        backgroundColor:"#fff",
    },
    addShop:{
        width:104.5,
        backgroundColor:"#f7ae3c",
        color:"#fff",
        fontSize:15,
        lineHeight:49,
        textAlign:"center",
        marginLeft:43,
    },
    pay:{
        width:104.5,
        backgroundColor:"#ea4a4a",
        color:"#fff",
        fontSize:15,
        lineHeight:49,
        textAlign:"center",
    },
    collect:{
         width:81,
         height:39,
         flexDirection:"row",
         justifyContent:"space-between",
    },
    kefu:{
        justifyContent:"space-between",
    },
    kefuImg:{
        width:22,
        height:21,
    },
    kefuTxt:{
        fontSize:11,
        color:"#888",
        textAlign:"center"
    },
    kefuView:{
        width:34,
        height:39,
        alignItems:"center",
        justifyContent:"space-between",
    },
    choose:{
        flex:1,
        fontSize:14,
        color:"#666",
        lineHeight:49,
        textAlign:"center",
    },
    mask:{
        flex:1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        position:"relative",
        justifyContent:"flex-end",
    },
    select:{
        width:width,
        height:390,
        backgroundColor:"#fff",
        borderBottomWidth:1,
        borderBottomColor:"#090723",
    },
    goodMes:{
        height:60,
        justifyContent:"flex-end",
        flexDirection: 'row',
        alignItems:"center"
    },
    goodImg:{
        width:100,
        height:100,
        position:"absolute",
        top:-25,
        left:12,
        zIndex:999,
    },
    close:{
        width:14,
        height:14,
        position:"absolute",
        right:12,
        top:12,
    },
    closeImg:{
        width:14,
        height:14,
    },
    goodPrice:{
        width:110,
        height:54,
        marginRight:127,
        justifyContent:"space-between",
    },
    totalPrice:{
        flexDirection:"row",
    },
    p1:{
        fontSize:12,
        color:"#ea4a4a",
        lineHeight:30,
    },
    p2:{
        fontSize:14,
        color:"#ea4a4a",
        lineHeight:30,
    },
    size:{
        marginTop:34,
        paddingLeft:12,
        paddingRight:12
    },
    sizeTit:{
        fontSize:15,
        color:"#333",
    },
    sizeList:{
        flexDirection:"row",
        flexWrap: 'wrap',
        marginTop:11,
    },
    tabActive:{
        height:30,
        backgroundColor:"#333",
        paddingLeft:10,
        paddingRight:10,
        borderRadius:15,
        marginRight:15,
        marginBottom:10,
    },
    tabStyle:{
        backgroundColor:"#fff",
        height:28,
        paddingLeft:10,
        paddingRight:10,
        borderRadius:15,
        borderColor:"#333",
        borderWidth:1,
        marginRight:15       ,
        marginBottom:10, 
    },
    activeTit:{
        height:30,
        fontSize:12,
        textAlign:"center",
        lineHeight:30,
        color:"#fff",
    },
    tabTit:{
        height:28,
        fontSize:12,
        textAlign:"center",
        lineHeight:28,
        color:"#333",
    },
    count:{
        marginTop:34,
        paddingLeft:12,
        paddingRight:12,
        flexDirection:"row",
    },
    countTit:{
        flex:1,
        height:35,
        fontSize:15,
        color:"#333",
        lineHeight:35
    },
    countBtn:{
        width:140,
        height:35,
        flexDirection:"row",
        borderColor:"#bbb",
        borderWidth:1,
        alignItems:"center",
    },
    countBack:{
        width:33,
        height:32,
        backgroundColor:"#f9f9f9",
        textAlign:"center",
        lineHeight:32,
        fontSize:16,
        borderRightColor:"#bbb",
        borderRightWidth:1,
    },
    countAdd:{
        width:33,
        height:32,
        backgroundColor:"#f9f9f9",
        textAlign:"center",
        lineHeight:32,
        fontSize:16,
        borderLeftColor:"#bbb",
        borderLeftWidth:1,
    },
    countNum:{
        flex:1,
        height:35,
        backgroundColor:"#fff",
        textAlign:"center",
        lineHeight:33,
        fontSize:14,
        borderTopColor:"#bbb",
        borderTopWidth:1,
        borderBottomColor:"#bbb",
        borderBottomWidth:1,
    },
    alertMask:{
        width:width,
        height:height,
        position:"absolute",
        left:0,
        bottom:0,
        justifyContent:"flex-end",
        backgroundColor:"rgba(0,0,0,0.5)"
    },
    shareBox:{
        height:250,
        backgroundColor:"#fff",
    },
    shareTitle:{
        fontSize:14,
        color:"#888",
        textAlign:"center",
        lineHeight:30,
        marginTop:15,
    },
    shareList:{
        flex:1,
        width:width,
        paddingLeft:30,
        paddingRight:30,
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"space-between",
    },
    shareQQ:{
        width:50,
        height:80,
        alignItems:"center",
        justifyContent:"space-between",
    },
    qqImg:{
        width:50,
        height:50,
    },
    qqTit:{
        textAlign:"center",
        fontSize:12,
        color:"#888",
    },
    cancelBtn:{
        width:width,
        height:50,
        fontSize:15,
        color:"#fff",
        backgroundColor:"#c444ff",
        textAlign:"center",
        lineHeight:50,
        fontWeight: 'bold',
    }
})