import { StyleSheet } from "react-native";
// 获取屏幕信息
var dimensions = require("Dimensions");
// 获取屏幕的宽度和高度
var { width, height } = dimensions.get("window");
export default styles = StyleSheet.create({
    container: {
        flex: 1,
        width: width,
    },
    header: {
        width: width,
        height: 45,
        backgroundColor: "#fff",
        position: "absolute",
        left: 0,
        top: 0,
        paddingLeft: 12,
        paddingRight: 12,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 999
    },
    search: {
        width: 256,
        height: 27.5,
        backgroundColor: "#f7f8f8",
        alignItems: "center",
        borderRadius: 20,
        position: "relative",
    },
    searchText: {
        padding: 0,
        fontSize: 12,
        color: "#888",
    },
    searchImg: {
        width: 17,
        height: 17,
        position: "absolute",
        top: 5,
        bottom: 0,
        right: 20,
    },
    newsImg: {
        width: 30,
        height: 30,
        position: "absolute",
        left: 10,
        bottom: 8,
    },
    RichScanImg: {
        width: 30,
        height: 30,
        position: "absolute",
        right: 10,
        bottom: 8,
    },
    content: {
        width: width,
        flex: 1,
    },
    conBox: {
        width: width,
        height: 186,
        marginTop: 45,
        backgroundColor: "#000",
    },
    classify: {
        width: width,
        height: 74,
        paddingTop: 30,
        paddingLeft: 20,
        paddingRight: 20,
        flexDirection: 'row',
        alignItems: "center",
        justifyContent: 'space-between',
    },
    classList: {
        width: 60,
        height: 70,
        flexDirection: "column",
        alignItems: "center",
        justifyContent: 'space-between',
    },
    listImg: {
        width: 33,
        height: 33,
    },
    listText: {
        textAlign: "center",
        fontSize: 13,
        color: "#666",
    },
    noticeList: {
        width: width,
        height: 67.5,
        paddingLeft: 19,
        paddingRight: 19,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: 'space-between',
        paddingTop: 25,
    },
    noticeLeft: {
        width: 41.5,
        height: 36,
    },
    noticeRight: {
        width: 230,
        height: 36,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: 'space-between',
    },
    hotText: {
        width: 20,
        height: 36,
        flexDirection: "column",
        justifyContent: 'space-between',
    },
    hot: {
        width: 20,
        height: 14.5,
        backgroundColor: "#ea4a4a",
        borderRadius: 5,
        fontSize: 12,
        textAlign: "center",
        lineHeight: 14.5,
        color: "#fff",
    },
    hotList: {
        width: 200.5,
        height: 36,
        flexDirection: "column",
        justifyContent: 'space-between',
    },
    list: {
        color: "#333",
        fontSize: 12,
        lineHeight: 14.5,
    },
    bigImg: {
        width: width,
        height: 80,
        marginTop: 19,
        marginBottom: 19,
        alignItems: "center",
    },
    picImg: {
        width: 350,
        height: 80,
        borderRadius: 5,
    },
    detailList: {
        width: width,
        flexDirection: "row",
        flexWrap: 'wrap',
        alignContent: 'center',
        justifyContent: 'space-between',
        paddingLeft: 10,
        paddingRight: 10,
    },
    every: {
        width: 168,
        height: 266,
        // backgroundColor: "red",
        marginBottom: 25,
    },
    imgBorder:{
        width: 168,
        height: 186,
        borderTopLeftRadius:20,
        borderTopRightRadius:20,
        backgroundColor:"#000",
        alignItems:"center",
    },
    teaImg: {
        width: 168,
        height: 186,
    },
    teaText:{
        width:168,
        height:66,
        flexDirection: "column",
        justifyContent: 'space-between',
        alignItems:"center",
        marginTop:9,
    },
    teaTitle:{
        width:168,
        height:14,
        fontSize:12,
        color:"#282828",
    },
    teaPrice:{
        width:168,
        height:43,
        flexDirection: "column",
        justifyContent: 'space-between',
        alignItems:"center",
    },
    bigPrice:{
        width:168,
        height:15,
        flexDirection: "row",
        justifyContent: 'space-between',
    },
    sales:{
        fontSize:10,
        color:"#888",
    },
    smallPrice:{
        width:168,
        height:15,
        flexDirection: "row",
        justifyContent: 'flex-start',
    },
    qian:{
        fontSize:13,
    }, 
    gifts:{
        fontSize:10,
        color:"#888",
        lineHeight:20,
        marginLeft: 15,
    },

})